FROM node:20-alpine

WORKDIR /app

# Копирование package.json и установка зависимостей
COPY package.json .
RUN npm install

# Копирование кода приложения
COPY . .

# Запуск приложения
CMD ["npm", "run", "dev"] 